# Generated by Django 5.2.3 on 2025-07-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentariocontacto_remove_comentario_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registros.alumnos', verbose_name='Alumno'),
            preserve_default=False,
        ),
    ]
